services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  backend:
    build: ./
    ports:
      - "5000:5000"
    environment:
      MONGODB_URL: mongodb://mongodb:27017/
      MONGODB_DBNAME: pinga
      JWT_PRIVATE_KEY: "secret"
    depends_on:
      - mongodb

volumes:
  mongodb:
